### ISSUE TITLE
Pytest or unittest?

### ISSUE THREAD

**Issue by TimoRJensen** [tofarr/servey#2]
https://github.com/tofarr/servey/blob/de8bc9416c1aa2b56b75f73374a7047f05380f6a/README.md?plain=1#L112

Why install pytest and then call unittest?

**Comment by tofarr** [comment]
Good point - I can drop the pytest dependency

**Comment by tofarr** [comment]
I use pytest for its code coverage plugin - I currently have it set to 98% but would like to get that to 100% when I get time:
(I suppose I could update the readme to use pytest instead of unittest, but this case is not doing anything special like checking coverage)
